-- Cohort Analysis [Customer Lifetime Value (CLV)]

WITH CTE1 AS
(SELECT
	CUSTOMERID,
    str_to_date(INVOICEDATE, '%m/%d/%Y %H:%i') AS FORMATTED_DATE,
    ROUND(QUANTITY*UNITPRICE, 2) AS SALE_VALUE
FROM RETAIL
WHERE 
	CUSTOMERID IS NOT NULL
    AND CUSTOMERID != ''
	AND INVOICENO NOT LIKE 'C%'
    AND QUANTITY > 0
    AND UNITPRICE > 0),
CTE2 AS    
(SELECT
	CUSTOMERID,
    FORMATTED_DATE AS PURCHASE_DATE,
    MIN(FORMATTED_DATE) OVER (PARTITION BY CUSTOMERID) AS FIRST_TRANSACTION_DATE,
    SALE_VALUE
FROM CTE1),

CTE3 AS
(SELECT 
	CUSTOMERID,
    FIRST_TRANSACTION_DATE,
    PURCHASE_DATE,
	SALE_VALUE,
	 TIMESTAMPDIFF(MONTH, FIRST_TRANSACTION_DATE, PURCHASE_DATE) AS COHORT_MONTH_NUM,
    DATE_FORMAT(FIRST_TRANSACTION_DATE, '%Y-%m-01') AS FIRST_TRANSACTION_MONTH
FROM CTE2)

SELECT
	FIRST_TRANSACTION_MONTH AS COHORT,
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 0 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_0",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 1 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_1",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 2 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_2",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 3 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_3",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 4 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_4",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 5 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_5",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 6 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_6",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 7 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_7",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 8 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_8",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 9 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_9",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 10 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_10",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 11 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_11",
    ROUND(SUM(CASE WHEN COHORT_MONTH_NUM = 12 THEN SALE_VALUE ELSE 0 END),0) AS "MONTH_12"
FROM CTE3
GROUP BY FIRST_TRANSACTION_MONTH
ORDER BY FIRST_TRANSACTION_MONTH;