-- Cohort Analysis [Customer Retention]

WITH CTE1 AS (
  SELECT
    CUSTOMERID,
    STR_TO_DATE(INVOICEDATE, '%m/%d/%Y %H:%i') AS FORMATTED_DATE
  FROM RETAIL
  WHERE CUSTOMERID IS NOT NULL AND CUSTOMERID!=''
    AND INVOICENO NOT LIKE 'C%' AND QUANTITY>0 AND UNITPRICE>0
),
CTE2 AS (
  SELECT
    CUSTOMERID,
    FORMATTED_DATE AS PURCHASE_DATE,
    MIN(FORMATTED_DATE) OVER (PARTITION BY CUSTOMERID) AS FIRST_TRANSACTION_DATE
  FROM CTE1
),
CTE3 AS (
  SELECT
    CUSTOMERID,
    DATE_FORMAT(FIRST_TRANSACTION_DATE, '%Y-%m-01') AS FIRST_TRANSACTION_MONTH,
    TIMESTAMPDIFF(MONTH, FIRST_TRANSACTION_DATE, PURCHASE_DATE) AS COHORT_MONTH_NUM
  FROM CTE2
)

SELECT
FIRST_TRANSACTION_MONTH AS COHORT,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 0  THEN CUSTOMERID END) AS MONTH_0,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 1  THEN CUSTOMERID END) AS MONTH_1,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 2  THEN CUSTOMERID END) AS MONTH_2,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 3  THEN CUSTOMERID END) AS MONTH_3,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 4  THEN CUSTOMERID END) AS MONTH_4,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 5  THEN CUSTOMERID END) AS MONTH_5,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 6  THEN CUSTOMERID END) AS MONTH_6,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 7  THEN CUSTOMERID END) AS MONTH_7,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 8  THEN CUSTOMERID END) AS MONTH_8,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 9  THEN CUSTOMERID END) AS MONTH_9,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 10 THEN CUSTOMERID END) AS MONTH_10,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 11 THEN CUSTOMERID END) AS MONTH_11,
COUNT(DISTINCT CASE WHEN COHORT_MONTH_NUM = 12 THEN CUSTOMERID END) AS MONTH_12

FROM CTE3
GROUP BY FIRST_TRANSACTION_MONTH
ORDER BY FIRST_TRANSACTION_MONTH;

