-- DROP DATABASE RETAIL_SALES;
CREATE DATABASE RETAIL_SALES;
use  retail_sales;

-- Truncate Retail;
-- drop table retail;

CREATE TABLE Retail (
    InvoiceNo VARCHAR(20),
    StockCode VARCHAR(20),
    Descriptions TEXT,
    Quantity INT,
    InvoiceDate VARCHAR(50), 
    UnitPrice DECIMAL(10,2),
    CustomerID INT,
    Country VARCHAR(50)
);


SELECT * FROM RETAIL;


-- Let's Explore the Data
SELECT * FROM RETAIL LIMIT 10;

SELECT COUNT(*) FROM retail; -- 541909

SELECT DISTINCT COUNTRY FROM RETAIL;

SELECT min(Quantity) FROM RETAIL; -- -80995

SELECT COUNT(*) FROM RETAIL
WHERE QUANTITY <= 0;-- 10624

SELECT COUNT(*) FROM RETAIL
WHERE INVOICENO LIKE 'C%';-- 9288

SELECT * FROM RETAIL
WHERE INVOICENO NOT LIKE 'C%' AND QUANTITY <= 0;

SELECT COUNT(*) FROM RETAIL
WHERE CUSTOMERID IS NULL; -- 135080

SELECT COUNT(*) FROM RETAIL
WHERE CUSTOMERID = ''; -- 0